spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/streamtest?serverTimezone=UTC+9
    username: root
    password: 12345678


logging:
  level:
    org.springframework.r2dbc.core: debug

jwt:
  secretKey: ${JWT_SECRET_KEY}

server:
  port: 8081